#!/bin/bash
# Set up Google Cloud Model Armor and Regional External Load Balancer
# Usage: ./setup_load_balancer.sh

set -e

# Load environment configuration
source "$(dirname "$0")/../set_env.sh"

echo "Configuring Model Armor and regional Load Balancer..."

# Ensure we are in the loadbalancer directory
cd "$(dirname "$0")"

# 1. Create Model Armor Security Template
echo "Creating Model Armor template '${ARMOR_TEMPLATE_ID}'..."
# Setup regional endpoint override for modelarmor tool
gcloud config set api_endpoint_overrides/modelarmor "https://modelarmor.${REGION}.rep.googleapis.com/"

if gcloud model-armor templates describe "${ARMOR_TEMPLATE_ID}" --location="${REGION}" >/dev/null 2>&1; then
    echo "Model Armor template '${ARMOR_TEMPLATE_ID}' already exists."
else
    gcloud model-armor templates create "${ARMOR_TEMPLATE_ID}" \
        --location="${REGION}" \
        --rai-settings-filters='[{ "filterType": "HATE_SPEECH", "confidenceLevel": "MEDIUM_AND_ABOVE" },{ "filterType": "HARASSMENT", "confidenceLevel": "MEDIUM_AND_ABOVE" },{ "filterType": "SEXUALLY_EXPLICIT", "confidenceLevel": "MEDIUM_AND_ABOVE" }]' \
        --basic-config-filter-enforcement=enabled \
        --pi-and-jailbreak-filter-settings-enforcement=enabled \
        --pi-and-jailbreak-filter-settings-confidence-level=LOW_AND_ABOVE \
        --malicious-uri-filter-settings-enforcement=enabled \
        --template-metadata-custom-llm-response-safety-error-code=798 \
        --template-metadata-custom-llm-response-safety-error-message="Guardian, a critical flaw has been detected in the response generated by the model!" \
        --template-metadata-custom-prompt-safety-error-code=799 \
        --template-metadata-custom-prompt-safety-error-message="Guardian, a critical flaw has been detected in the prompt you are attempting to send!" \
        --template-metadata-ignore-partial-invocation-failures \
        --template-metadata-log-operations \
        --template-metadata-log-sanitize-operations
fi

# 2. Check for Cloud Run services and create Serverless NEGs
VLLM_SERVICE="gemma-vllm-fuse-service"
OLLAMA_SERVICE="gemma-ollama-baked-service"

HAS_VLLM=false
HAS_OLLAMA=false

if gcloud run services describe "${VLLM_SERVICE}" --region="${REGION}" >/dev/null 2>&1; then
    HAS_VLLM=true
    echo "Found service ${VLLM_SERVICE}. Creating Serverless NEG..."
    if ! gcloud compute network-endpoint-groups describe "serverless-vllm-neg" --region="${REGION}" >/dev/null 2>&1; then
        gcloud compute network-endpoint-groups create "serverless-vllm-neg" \
            --region="${REGION}" \
            --network-endpoint-type="serverless" \
            --cloud-run-service="${VLLM_SERVICE}"
    fi
else
    echo "WARNING: Service ${VLLM_SERVICE} not found. Run ./deploy_vllm.sh first."
fi

if gcloud run services describe "${OLLAMA_SERVICE}" --region="${REGION}" >/dev/null 2>&1; then
    HAS_OLLAMA=true
    echo "Found service ${OLLAMA_SERVICE}. Creating Serverless NEG..."
    if ! gcloud compute network-endpoint-groups describe "serverless-ollama-neg" --region="${REGION}" >/dev/null 2>&1; then
        gcloud compute network-endpoint-groups create "serverless-ollama-neg" \
            --region="${REGION}" \
            --network-endpoint-type="serverless" \
            --cloud-run-service="${OLLAMA_SERVICE}"
    fi
else
    echo "Ollama service '${OLLAMA_SERVICE}' not deployed. Skipping Ollama NEG creation."
fi

if [ "$HAS_VLLM" = false ] && [ "$HAS_OLLAMA" = false ]; then
    echo "ERROR: Neither vLLM nor Ollama service is deployed. Cannot configure Load Balancer."
    exit 1
fi

# 3. Create Backend Services
echo "Creating backend services..."
if ! gcloud compute backend-services describe "vllm-backend-service" --region="${REGION}" >/dev/null 2>&1; then
    gcloud compute backend-services create "vllm-backend-service" \
        --load-balancing-scheme="EXTERNAL_MANAGED" \
        --protocol="HTTPS" \
        --region="${REGION}"
fi

if [ "$HAS_VLLM" = true ]; then
    # Add backend if not already added
    if ! gcloud compute backend-services describe "vllm-backend-service" --region="${REGION}" --format="value(backends)" | grep -q "serverless-vllm-neg"; then
        gcloud compute backend-services add-backend "vllm-backend-service" \
            --network-endpoint-group="serverless-vllm-neg" \
            --network-endpoint-group-region="${REGION}"
    fi
fi

if [ "$HAS_OLLAMA" = true ]; then
    if ! gcloud compute backend-services describe "ollama-backend-service" --region="${REGION}" >/dev/null 2>&1; then
        gcloud compute backend-services create "ollama-backend-service" \
            --load-balancing-scheme="EXTERNAL_MANAGED" \
            --protocol="HTTPS" \
            --region="${REGION}"
    fi
    if ! gcloud compute backend-services describe "ollama-backend-service" --region="${REGION}" --format="value(backends)" | grep -q "serverless-ollama-neg"; then
        gcloud compute backend-services add-backend "ollama-backend-service" \
            --network-endpoint-group="serverless-ollama-neg" \
            --network-endpoint-group-region="${REGION}"
    fi
fi

# 4. Generate Self-Signed SSL Certificate for HTTPS
echo "Generating self-signed SSL certificate..."
if ! gcloud compute ssl-certificates describe "agentverse-ssl-cert-self-signed" --region="${REGION}" >/dev/null 2>&1; then
    openssl genrsa -out agentverse.key 2048
    openssl req -new -x509 -key agentverse.key -out agentverse.crt -days 365 \
      -subj "/C=US/ST=CA/L=MTV/O=Agentverse/OU=Guardians/CN=internal.agentverse"
    
    gcloud compute ssl-certificates create "agentverse-ssl-cert-self-signed" \
        --certificate="agentverse.crt" \
        --private-key="agentverse.key" \
        --region="${REGION}"
    # Clean up local cert files
    rm agentverse.key agentverse.crt
else
    echo "Self-signed certificate 'agentverse-ssl-cert-self-signed' already exists."
fi

# 5. Create URL Map
echo "Creating URL map..."
if ! gcloud compute url-maps describe "agentverse-lb-url-map" --region="${REGION}" >/dev/null 2>&1; then
    # Default backend is vLLM (or Ollama if vLLM isn't present)
    DEFAULT_BACKEND="vllm-backend-service"
    if [ "$HAS_VLLM" = false ]; then
        DEFAULT_BACKEND="ollama-backend-service"
    fi
    
    gcloud compute url-maps create "agentverse-lb-url-map" \
        --default-service="${DEFAULT_BACKEND}" \
        --region="${REGION}"
        
    # If Ollama exists and vLLM is default, add routing rules for Ollama
    if [ "$HAS_OLLAMA" = true ] && [ "$DEFAULT_BACKEND" = "vllm-backend-service" ]; then
        gcloud compute url-maps add-path-matcher "agentverse-lb-url-map" \
            --default-service="vllm-backend-service" \
            --path-matcher-name="api-path-matcher" \
            --path-rules='/api/*=ollama-backend-service' \
            --region="${REGION}"
    fi
else
    echo "URL map 'agentverse-lb-url-map' already exists."
fi

# 6. Create Target HTTPS Proxy
echo "Creating Target HTTPS Proxy..."
if ! gcloud compute target-https-proxies describe "agentverse-https-proxy" --region="${REGION}" >/dev/null 2>&1; then
    gcloud compute target-https-proxies create "agentverse-https-proxy" \
        --url-map="agentverse-lb-url-map" \
        --ssl-certificates="agentverse-ssl-cert-self-signed" \
        --region="${REGION}"
else
    echo "Target HTTPS Proxy 'agentverse-https-proxy' already exists."
fi

# 7. Reserve Static External IP Address
echo "Reserving static IP address..."
if ! gcloud compute addresses describe "agentverse-lb-ip" --region="${REGION}" >/dev/null 2>&1; then
    gcloud compute addresses create "agentverse-lb-ip" --region="${REGION}"
else
    echo "Static IP 'agentverse-lb-ip' already reserved."
fi

# Retrieve the IP
LB_IP=$(gcloud compute addresses describe "agentverse-lb-ip" --region="${REGION}" --format="value(address)")
echo "Reserved Load Balancer IP: ${LB_IP}"

# 8. Create Forwarding Rule
echo "Creating forwarding rule..."
if ! gcloud compute forwarding-rules describe "agentverse-forwarding-rule" --region="${REGION}" >/dev/null 2>&1; then
    gcloud compute forwarding-rules create "agentverse-forwarding-rule" \
        --address="agentverse-lb-ip" \
        --target-https-proxy="agentverse-https-proxy" \
        --target-https-proxy-region="${REGION}" \
        --ports="443" \
        --load-balancing-scheme="EXTERNAL_MANAGED" \
        --region="${REGION}"
else
    echo "Forwarding rule 'agentverse-forwarding-rule' already exists."
fi

# 9. Configure and Import Model Armor Service Extension
echo "Compiling Service Extension template..."
python3 -c "
import os
with open('service_extension.template.yaml') as f:
    template = f.read()
for var in ['PROJECT_ID', 'REGION', 'MODEL_PATH', 'ARMOR_TEMPLATE_ID']:
    template = template.replace('\${' + var + '}', os.environ[var])
with open('service_extension.yaml', 'w') as f:
    f.write(template)
"

echo "Importing Service Extension..."
gcloud service-extensions lb-traffic-extensions import "chain-model-armor-unified" \
    --source="service_extension.yaml" \
    --location="${REGION}" \
    --quiet

# 10. Grant necessary permissions to the Service Extension Service Agent
PROJECT_NUMBER=$(gcloud projects describe "${PROJECT_ID}" --format="value(projectNumber)")
SERVICE_AGENT="service-${PROJECT_NUMBER}@gcp-sa-dep.iam.gserviceaccount.com"
echo "Granting roles to Service Extensions Service Agent: ${SERVICE_AGENT}..."

gcloud projects add-iam-policy-binding "${PROJECT_ID}" \
    --member="serviceAccount:${SERVICE_AGENT}" \
    --role="roles/container.admin" \
    --quiet

gcloud projects add-iam-policy-binding "${PROJECT_ID}" \
    --member="serviceAccount:${SERVICE_AGENT}" \
    --role="roles/modelarmor.calloutUser" \
    --quiet

gcloud projects add-iam-policy-binding "${PROJECT_ID}" \
    --member="serviceAccount:${SERVICE_AGENT}" \
    --role="roles/serviceusage.serviceUsageConsumer" \
    --quiet

gcloud projects add-iam-policy-binding "${PROJECT_ID}" \
    --member="serviceAccount:${SERVICE_AGENT}" \
    --role="roles/modelarmor.user" \
    --quiet

echo "========================================="
echo "Load Balancer & Security Gateway Setup Complete!"
echo "Public HTTPS Endpoint: https://${LB_IP}"
echo "Note: The load balancer uses a self-signed certificate. Use '-k' (insecure) flag with curl."
echo "========================================="
